#!/bin/sh

run(){
    eval "su - nginx -s /bin/ash -c 'cd /var/www/nextcloud/ && "$@"'" 
    return $? 
}

if [ -f /tmp/nextcloud_configured ] && [ $(cat /tmp/nextcloud_configured) -eq 0 ]
then
    run php cron.php
fi