#!/usr/bin/with-contenv sh
if [ -z "$(ls -A "/var/www/nextcloud")" ]; 
then 
	if [ ! -d /var/www/nextcloud ]; 
	then 
		mkdir /var/www/nextcloud 
	fi 
	wget https://download.nextcloud.com/server/releases/nextcloud-${VERSION}.zip -O /tmp/nextcloud-${VERSION}.zip 
	unzip /tmp/nextcloud-${VERSION}.zip -d /var/www/ 
	rm /tmp/nextcloud-${VERSION}.zip 
	chown nginx:nginx /var/www/nextcloud -R
	CMD=$(echo 'cd /var/www/nextcloud/ && php occ maintenance:install  --database "mysql" --database-host "'${DATABASE_HOST}'" --database-port "'${DATABASE_PORT}'" --database-name "'${DATABASE_NAME}'" --database-user "'${DATABASE_USERNAME}'" --database-pass "'${DATABASE_PASSWORD}'" --admin-user "'${ADMIN_USERNAME}'" --admin-pass "'${ADMIN_PASSWORD}'"')
	eval "su - nginx -s /bin/ash -c '"$CMD"'" 

    while [ 1 -eq 1 ];
    do    
        NAME="TRUSTED_DOMAIN_"$COUNTER
        HOST=$(eval 'echo $'$NAME)
        if [ -z "$HOST" ];
        then 
            break
        fi
        CMD=$(echo 'cd /var/www/nextcloud/ && php occ config:system:set trusted_domains '$COUNTER' --value='$HOST)
	    eval "su - nginx -s /bin/ash -c '"$CMD"'" 

    done

    


fi
